yarnPath: .yarn/releases/yarn-berry.cjs

nodeLinker: node-modules

# not working, it should potentially resolve pnp errors
# packageExtensions:
#   '@nrwl/next@*':
#     dependencies:
#       dotenv: '*'
